Random numbers functions
htmlacademy-javascript/1467059-keksobooking-25 pull request #2
Opened 2022-02-20 17:52 UTC by Bazhko

2022-02-21 07:34 UTC, ant1quar requested changes

2022-02-21 07:34 UTC, ant1quar commented on js/main.js
> +  return result.toFixed(float);
тут будет ошибка, если пользователь ввел некорректный диапазон и в result попала строка, над которой вызовется toFixed()
Попробуй переделать так, чтобы toFixed вызывался только если мы получили число

2022-02-21 07:34 UTC, ant1quar commented on js/main.js
> +  return result;
Тут не нужна лишняя переменная. можешь сходу возвращать то, что вычисляешь
```suggestion
  return (min >= 0 && min < max) ? Math.floor(Math.random() * (max - min + 1) + min) : 'Введите корректный диапозон от 0 и выше';
```

2022-02-22 04:42 UTC, Bazhko commented on js/main.js
> +  return result.toFixed(float);
исправил

2022-02-22 04:42 UTC, Bazhko commented on js/main.js
> +  return result;
Исправил

2022-02-23 08:32 UTC, merged